# Generated by Django 6.0.7 on 2026-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_descriptions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='JobDescriptions',
        ),
    ]
